version: '3.8'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 8081:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MAX_EXECUTION_TIME: 3600
            MYSQL_ROOT_PASSWORD: qwerty
        volumes:
            - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: rywalizer
            MYSQL_ROOT_PASSWORD: qwerty
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306
    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - /var/www/vendor
        depends_on:
            - mysql